-- Calling the cli locally or through an ssh connection
cliLocation:   local
chainIndexUrl: "http://localhost:9084"
networkId:     Mainnet

-- Directory name of the script and data files
scriptFileDir:      ".local-cluster/scripts"

-- Directory for the signing key file(s)
signingKeyFileDir:  ".wallets"

-- Directory where the encoded transaction files will be saved
txFileDir:          ".local-cluster/txs"

-- | Directory name of metadata files
metadataDir:         ".local-cluster/metadata"

-- Dry run mode will build the tx, but skip the submit step
dryRun:             false
logLevel:           debug
port:               9080
enableTxEndpoint:   true

-- Save some stats during contract run (only transactions execution budgets supported atm)
collectStats: true

-- Save logs from contract execution: pab request logs and contract logs
collectLogs: true
